export MUJOCO_ROOT=$(pwd)/.mujoco
export MUJOCO_PY_MUJOCO_PATH=${MUJOCO_ROOT}/mujoco200
export MUJOCO_PY_MJKEY_PATH="${MUJOCO_PY_MJKEY_PATH:-${MUJOCO_ROOT:-$HOME/.mujoco}/mjkey.txt}"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${MUJOCO_PY_MUJOCO_PATH}/bin